import test from 'node:test';
import assert from 'node:assert/strict';
import {connect} from './hid.mjs';
import {models,encodeKey,equivalent} from './protocol.mjs';
const report=(id,size=8)=>({reportId:id,items:[{reportSize:8,reportCount:size}]});
class FakeDevice extends EventTarget {
 constructor(model=models[0]){super();this.vendorId=0x3553;this.productId=model.pid;this.model=model;this.opened=false;this.records=Array.from({length:model.slots},(_,i)=>encodeKey(String.fromCharCode(97+i)));this.calls=[];this.collections=[{usagePage:1,usage:0,children:[],featureReports:[],inputReports:[report(model.reportId)],outputReports:[report(model.reportId)]}];}
 async open(){this.opened=true;}
 async close(){this.opened=false;}
 emit(bytes,id=this.model.reportId){const e=new Event('inputreport');e.device=this;e.reportId=id;e.data=new DataView(Uint8Array.from(bytes).buffer);this.dispatchEvent(e);}
 async sendReport(id,bytes){this.calls.push({id,bytes:[...bytes]});if(this.fail)throw Error('transport failed');if(this.hang)return new Promise(()=>{});if(this.pending){this.records[this.pending-1]=bytes.slice(0,bytes[0]);this.pending=0;return;}if(bytes[1]===0x82){if(this.ack)this.emit([0x81,0x55,0,0,0,0,0,0]);const b=new Uint8Array(8);b.set(this.records[bytes[3]-1]);this.emit(this.bad??b,this.badId??id);}else if(bytes[1]===0x81)this.pending=bytes[3];}
}
class FakeHID extends EventTarget {constructor(device){super();this.device=device;}async requestDevice(options){this.options=options;return [this.device];}}
async function fixture(model){const device=new FakeDevice(model);const hid=new FakeHID(device);return {device,hid,client:await connect(hid)};}
test('explicit selection filters and report framing for both models',async()=>{for(const model of models){const {device,hid,client}=await fixture(model);device.ack=true;assert.deepEqual(await client.readAll(),device.records);assert.equal(hid.options.filters.length,2);for(const f of hid.options.filters){assert.equal(f.vendorId,0x3553);assert.equal(f.usagePage,1);assert.equal(f.usage,0);}assert.deepEqual(device.calls[0],{id:model.reportId,bytes:[1,0x82,8,1,0,0,0,0]});await client.close();}});
test('malformed collections and product rejected before open',async()=>{for(const mutate of [d=>d.productId=9,d=>d.collections[0].usage=6,d=>d.collections[0].outputReports[0]=report(0,9),d=>d.collections[0].featureReports=[report(0)]]){const d=new FakeDevice();mutate(d);await assert.rejects(connect(new FakeHID(d)));assert.equal(d.opened,false);}});
test('malformed reports close connection',async()=>{for(const mutate of [d=>d.bad=[4,1,0,4],d=>d.badId=9,d=>d.bad=[1,1,0,4,0,0,0,0]]){const {device,client}=await fixture();mutate(device);await assert.rejects(client.readAll());assert.equal(device.opened,false);await assert.rejects(client.readAll());}});
test('apply changes only selected slot and checks all records',async()=>{const {device,client}=await fixture();const before=await client.readAll();const target=before.map(b=>b.slice());target[1]=encodeKey('ctrl+z');const result=await client.apply(target,before);assert.equal(equivalent(result[1],target[1]),true);assert.deepEqual(device.records[0],before[0]);assert.deepEqual(device.records[2],before[2]);assert.deepEqual(device.calls.filter(c=>c.bytes[1]===0x81).map(c=>c.bytes[3]),[2]);await client.close();});
test('stale originals and no-op cause no configuration writes',async()=>{const {device,client}=await fixture();const before=await client.readAll();await client.apply(before,before);assert.equal(device.calls.filter(c=>c.bytes[1]===0x81).length,0);device.records[2]=encodeKey('x');await assert.rejects(client.apply(before,before),/changed|stale/i);assert.equal(device.calls.filter(c=>c.bytes[1]===0x81).length,0);await client.close();});
test('unsupported originals rejected before querying or writing',async()=>{const {device,client}=await fixture();const before=await client.readAll();before[1]=Uint8Array.of(2,99);const n=device.calls.length;await assert.rejects(client.apply(before,before));assert.equal(device.calls.length,n);await client.close();});
test('failed I/O invalidates, disconnection and concurrent calls reject',async()=>{const {device,hid,client}=await fixture();device.fail=true;await assert.rejects(client.readAll());assert.equal(device.opened,false);const next=await fixture();next.device.hang=true;const operation=next.client.readAll();await assert.rejects(next.client.readAll(),/busy|progress/i);const event=new Event('disconnect');event.device=next.device;next.hid.dispatchEvent(event);await assert.rejects(operation);await assert.rejects(next.client.readAll());});
test('timeout invalidates a delayed send',async()=>{const {device,client}=await fixture();device.hang=true;await assert.rejects(client.readAll(),/timed out/i);assert.equal(device.opened,false);await assert.rejects(client.readAll());});
test('supported second collection is accepted; unknown or duplicate reports are rejected',async()=>{const d=new FakeDevice(models[1]);d.collections.push({usagePage:1,usage:0,children:[],featureReports:[],inputReports:[report(2,15)],outputReports:[]});const c=await connect(new FakeHID(d));await c.close();for(const mutate of [d=>d.collections[0].inputReports.push(report(1)),d=>d.collections[0].inputReports.push(report(2,16)),d=>d.collections[0].children.push({}),d=>d.collections[0].outputReports.push(report(2))]){const bad=new FakeDevice(models[1]);mutate(bad);await assert.rejects(connect(new FakeHID(bad)));}});
test('programming failure stops before later slots',async()=>{const {device,client}=await fixture();const before=await client.readAll();const target=before.map(()=>encodeKey('x'));const originalSend=device.sendReport.bind(device);device.sendReport=async(id,bytes)=>{if(bytes[1]===0x81){device.fail=true;}return originalSend(id,bytes);};await assert.rejects(client.apply(target,before));assert.equal(device.opened,false);assert.deepEqual(device.calls.filter(c=>c.bytes[1]===0x81).map(c=>c.bytes[3]),[1]);assert.deepEqual(device.records,before);});
test('readback mismatch invalidates connection',async()=>{const {device,client}=await fixture();const before=await client.readAll();const target=before.map(b=>b.slice());target[0]=encodeKey('x');const originalSend=device.sendReport.bind(device);device.sendReport=async(id,bytes)=>{if(device.pending){device.pending=0;device.calls.push({id,bytes:[...bytes]});return;}return originalSend(id,bytes);};await assert.rejects(client.apply(target,before),/Readback/);assert.equal(device.opened,false);});
test('endless ACKs do not reset the read deadline',async()=>{const {device,client}=await fixture();device.sendReport=async()=>{};const interval=setInterval(()=>device.emit([0x81,0x55,0,0,0,0,0,0]),30);try{await assert.rejects(client.readAll(),/timed out/i);assert.equal(device.opened,false);}finally{clearInterval(interval);}});
test('matchesDevice distinguishes same-model physical device objects',async()=>{const {device,client}=await fixture();assert.equal(client.matchesDevice(device),true);assert.equal(client.matchesDevice(new FakeDevice(device.model)),false);assert.equal(client.matchesDevice(null),false);await client.close();});
